name: GuizhanCraft
version: '${project.version}'
main: dev.ybw0014.guizhancraft.implementation.GuizhanCraft
api-version: 1.16
authors: [ ybw0014 ]
description: A Slimefun Addon
depend:
  - Slimefun
softdepend:
  - ElectricSpawners
commands:
  sfspawner:
    description: /sfspawner
    usage: /sfspawner <sub>
    aliases: [ sfs ]
