name: GuizhanCraft
version: '${project.version}'
main: net.guizhanss.guizhancraft.GuizhanCraft
api-version: 1.14
depend: [ Slimefun ]
authors: [ ybw0014 ]
description: A Slimefun Addon
commands:
  sfspawner:
    description: /sfspawner
    usage: /sfspawner <sub>
    aliases: [ sfs ]