name: Blob Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK ${{ vars.BUILDS_JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ vars.BUILDS_JAVA_VERSION }}
          distribution: temurin

      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle
        run: ./gradlew clean shadowJar

      - name: Rename jar file
        run: mv build/libs/GuizhanCraft-*.jar build/libs/GuizhanCraft.jar

      - name: Upload to Blob Builds
        uses: WalshyDev/blob-builds/gh-action@main
        with:
          project: GuizhanCraft
          file: ./build/libs/GuizhanCraft.jar
          apiToken: ${{ secrets.BLOB_BUILDS_API_TOKEN }}
          releaseNotes: ${{ github.event.head_commit.message }}
